# Generated by Django 4.1 on 2022-09-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemWishlist',
        ),
    ]
